{
  allOrgCharts {
    edges {
      node {
        id
        documentHash
        orgChartUrl {
          organisationEntity {
            name
          }
        }
        createdAt
        document
        status
      }
    }
  }
}