query orgChart($id: ID!) {
  orgChart(id: $id) {
    id
    status
    document
    createdAt
    rawSource
    orgChartUrl {
      url
      organisationEntity {
        id
        name
        shortName
        locations {
          edges {
            node {
              id
              name
              street
              postalCode
              city
            }
          }
        }
      }
    }
  }
}